/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Fetch recent messages from a channel. Returns JSON string. */
export declare function history(channelId: string, limit?: number | undefined | null): Promise<string>

/** List conversations (channels + DMs). Returns JSON string. */
export declare function listConversations(): Promise<string>

/** Get replies in a thread. Returns JSON string. */
export declare function replies(channelId: string, threadTs: string, limit?: number | undefined | null): Promise<string>

/** Resolve @user or #channel name to a channel/DM ID. */
export declare function resolveChannel(refStr: string): Promise<string>

/** Search messages across workspace. Returns JSON string. */
export declare function search(query: string): Promise<string>

/** Send a message. Returns the message timestamp. */
export declare function send(channel: string, text: string, threadTs?: string | undefined | null): Promise<string>

/** Look up a user's display name by ID. */
export declare function userName(userId: string): Promise<string>
